# Generated by Django 2.2.2 on 2019-12-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'social_network_blog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SocialNetworkCustomuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'social_network_customuser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SocialNetworkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.SocialNetworkBlog')),
            ],
            options={
                'db_table': 'social_network_post',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='socialnetworkblog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.SocialNetworkCustomuser', unique=True),
        ),
        migrations.CreateModel(
            name='SocialNetworkRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.SocialNetworkPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.SocialNetworkCustomuser')),
            ],
            options={
                'db_table': 'social_network_rate',
                'managed': True,
                'unique_together': {('user', 'post')},
            },
        ),
    ]
